spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: validate

  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/code-group
    username: user
    password: password
    driverClassName: org.postgresql.Driver